name: routine_clock
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0+2
  path_provider: ^1.6.10
  shared_preferences: ^0.5.7+3
  shared_preferences_web: ^0.1.2+7
  uuid: ^2.0.4
  flutter_vibrate: ^1.0.0

  cupertino_icons: ^0.1.3
  flutter_neumorphic: ^3.0.1
  analog_clock: ^0.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
